system:
  app_id: 00000000-00000000-00000000
logger:
  console: true
  remote: false
micro:
  run: 127.0.0.1:1024
  dns: test.lhdht.com:80
  endpoint: 101.120.1.125:1024|192.168.1.101:1024
  namespace: /microservice/firefly
task:
  max_cache: 100
  max_concurrency: 1
  min_concurrency: 0