system:
  app_id: 00000000-00000000-00000000
  run_port:
logger:
  console: true
  enable: true
  use_remote: true
micro:
  address:
  namespace: /microservice/lhdht/test
  max_retry: 5
  ttl: 5
grpc:
  deploy: false
  address:
