logger:
  console: true
  enable: true
micro:
  deploy: NAN
  gateway_name:
  namespace:
  ttl: 5
  address:
    inside:
    outside:
  register_center:
    name:
    mode:
    auth:
    address:
    normal:
      account:
      password:
    tls:
      ca_cert:
      server_cert:
      server_cert_key:
