system:
  app_id: 1111111111-11111111-11111111
logger:
  console: true
  enable: true
  use_remote: true
micro:
  address:
  namespace: /microservice/lhdht/test
  max_retry: 5
  ttl: 5
grpc:
  deploy: false
  address: 127.0.0.1:10506
